source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "3.2.2"

# Rails framework
gem "rails", "~> 7.0.8"

# Use mongoid as the database
gem "mongoid", "~> 7.5"

# Twilio for sending SMS
gem 'twilio-ruby'

# Web server
gem "puma", "~> 5.0"

# Platform-specific timezone support
gem "tzinfo-data", platforms: %i[ mingw mswin x64_mingw jruby ]

# Speed up boot time
gem "bootsnap", require: false

# Handle CORS
gem "rack-cors"

# User authentication
gem "devise"

# Development and Test specific gems
group :development, :test do
  gem 'dotenv-rails' # Load env vars from .env in dev/test only
  gem "debug", platforms: %i[ mri mingw x64_mingw ]
end

group :development do
  # Speeds up dev commands
  # gem "spring"
end
